
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Header from "@/components/ui/Header";
import ReduxProvider from "@/components/clientComponents/ReduxProvider";
import { Toaster } from 'react-hot-toast';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* redux provider */}
        <ReduxProvider >
          <div className="max-w-7xl mx-auto px-1 py-2 ">
            <Header />
          </div>
          <Navbar />
          <div className="max-w-7xl mx-auto px-1 py-2 ">
            {children}
          </div>
        </ReduxProvider>
        <Toaster />
      </body>
    </html >
  );
}
